// =============================================================================
// packages/shared/src/index.ts
// Barrel re-export — import from '@duseum/shared' in Lambda handlers
// =============================================================================

export * from './types/index.js'
export * from './errors/index.js'
export * from './db/client.js'
export * from './auth/access-control.js'
export * from './secrets.js'
export * from './notifications/index.js'
export * from './features/index.js'
export * from './db/users.repository.js'
export * from './db/authors.repository.js'
export * from './db/collections.repository.js'
export * from './db/upload-intents.repository.js'
export * from './db/artworks.repository.js'
export * from './db/subscriptions.repository.js'
export * from './db/idempotency.repository.js'
export * from './db/weekly-feature-bookings.repository.js'
export * from './db/config.repository.js'
export * from './db/comments.repository.js'
export * from './db/reactions.repository.js'
export * from './db/follows.repository.js'
export * from './db/notification-preferences.repository.js'
export * from './auth/unsubscribe-token.js'
export * from './stripe/index.js'
export * from './s3/index.js'
export * from './s3/cloudfront-signer.js'
export * from './sqs/index.js'
export * from './middleware/logger.js'
export * from './middleware/auth.js'
export * from './middleware/admin-auth.js'
export * from './middleware/error-handler.js'
export * from './middleware/validate-body.js'
export * from './middleware/responses.js'
export * from './middleware/handler-template.js'
